basePath: /api/v1
definitions:
  entities.Doctor:
    properties:
      created_at:
        type: string
      full_name:
        example: Иванов Иван Иванович
        type: string
      id:
        type: integer
      phone:
        example: "+79991234567"
        type: string
      updated_at:
        type: string
    type: object
  entities.Flg:
    properties:
      date:
        example: "2023-10-15T14:30:00Z"
        type: string
      id:
        example: 1
        type: integer
      is_completed:
        type: boolean
      number:
        example: 984212
        type: integer
      organization:
        example: Stavropol
        type: string
      result:
        example: COVID
        type: string
    type: object
  entities.Manager:
    properties:
      full_name:
        example: Иванов Иван Иванович
        type: string
      id:
        type: integer
      phone:
        example: "+79991234567"
        type: string
    type: object
  entities.Patient:
    properties:
      birth_date:
        example: "1980-05-15T00:00:00Z"
        type: string
      created_at:
        type: string
      division:
        example: Прогер
        type: string
      flg:
        $ref: '#/definitions/entities.Flg'
      full_name:
        example: Иванов Иван Иванович
        type: string
      id:
        example: 1
        type: integer
      is_male:
        example: true
        type: boolean
      organization_id:
        example: 1
        type: integer
      position:
        example: Прогер
        type: string
      statistics:
        $ref: '#/definitions/entities.PatientStatistics'
      updated_at:
        type: string
      vaccines:
        items:
          $ref: '#/definitions/entities.Vaccine'
        type: array
    type: object
  entities.PatientStatistics:
    properties:
      completed_analysis_items:
        type: integer
      completed_receptions:
        type: integer
      id:
        type: integer
      patient_id:
        type: integer
      total_analysis_orders:
        description: Статистика по анализам
        type: integer
      total_receptions:
        description: Статистика по приемам
        type: integer
      updated_at:
        type: string
    type: object
  entities.Vaccine:
    properties:
      body_part_id:
        type: integer
      certificate_number_id:
        type: integer
      date:
        type: string
      dose_id:
        type: integer
      id:
        type: integer
      is_completed:
        type: boolean
      is_exemption:
        type: boolean
      is_refusal:
        description: Булевые флаги определяют подтип формы
        type: boolean
      med_withdrawl_num:
        description: Поле для медотвода
        type: integer
      medication_id:
        type: integer
      method_id:
        type: integer
      number_id:
        type: integer
      patientID:
        type: integer
      place_id:
        type: integer
      result:
        description: Полная прививка
        type: string
      titer_amount:
        description: Поле для титра
        type: integer
      title_id:
        description: Так же должно быть и для титра
        type: integer
    type: object
  handlers.IncorrectDataError:
    properties:
      response:
        properties:
          code:
            example: 401
            type: integer
          message:
            example: Некорректные данные
            type: string
        type: object
      status:
        description: error
        example: IncorrectDataError
        type: string
    type: object
  handlers.IncorrectFormatError:
    properties:
      response:
        properties:
          code:
            example: 400
            type: integer
          message:
            example: Неверный формат запроса
            type: string
        type: object
      status:
        description: error
        example: IncorrectFormatError
        type: string
    type: object
  handlers.InternalServerError:
    properties:
      response:
        properties:
          code:
            example: 500
            type: integer
          message:
            example: Внутренняя ошибка сервера
            type: string
        type: object
      status:
        description: error
        example: InternalServerError
        type: string
    type: object
  handlers.NotFoundError:
    properties:
      response:
        properties:
          code:
            example: 404
            type: integer
          message:
            example: Данные не найдены
            type: string
        type: object
      status:
        description: error
        example: NotFoundError
        type: string
    type: object
  handlers.ResultError:
    properties:
      response:
        properties:
          code:
            description: '[RULE]: must be one of codes from table (Check DEV.PAGE)'
            example: 400
            type: integer
          message:
            example: Bad request
            type: string
        type: object
      status:
        description: error
        example: error
        type: string
    type: object
  handlers.ValidationError:
    properties:
      response:
        properties:
          code:
            example: 422
            type: integer
          message:
            example: Ошибка валидации
            type: string
        type: object
      status:
        description: error
        example: ValidationError
        type: string
    type: object
  models.CreatePatientRequest:
    description: Данные для создания нового пациента
    properties:
      birth_date:
        description: Дата рождения
        example: "1980-05-15"
        type: string
      full_name:
        description: ФИО пациента
        example: Смирнов Алексей Петрович
        type: string
      is_male:
        description: Пол (true - мужской)
        example: true
        type: boolean
    type: object
  models.DoctorAuthResponse:
    description: Ответ с данными авторизованного врача
    properties:
      id:
        description: ID врача
        example: 1
        type: integer
      token:
        description: JWT токен
        example: eyJhbGciOi...
        type: string
    type: object
  models.DoctorLoginRequest:
    description: Запрос для входа врача в систему
    properties:
      password:
        description: Пароль
        example: "123"
        type: string
      phone:
        description: Логин (телефон)
        example: "+79622840765"
        type: string
    required:
    - password
    - phone
    type: object
  models.OrganizationShortResponse:
    properties:
      id:
        type: integer
      manager:
        $ref: '#/definitions/entities.Manager'
      title:
        type: string
    type: object
  models.PatientGroupShortResponse:
    properties:
      code:
        example: "94928490"
        type: string
      created_at:
        example: "2023-05-15T14:30:00Z"
        type: string
      id:
        type: integer
      organization:
        example: medlab
        type: string
    type: object
  models.PatientsListResponse:
    properties:
      currentPage:
        type: integer
      hits:
        items:
          $ref: '#/definitions/entities.Patient'
        type: array
      hitsPerPage:
        type: integer
      totalHits:
        type: integer
      totalPages:
        type: integer
    type: object
  models.UpdateDoctorRequest:
    description: Используется для изменения информации о враче
    properties:
      full_name:
        example: Иванов Иван Иванович
        type: string
      id:
        example: 1
        type: integer
      login:
        example: "+79123456789"
        type: string
      specialization_id:
        example: 1
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
  description: API для работы с приёмами пациентов
  title: ClinicHub API
  version: 1.0.0
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: Аутентифицирует врача по номеру телефона и паролю
      parameters:
      - description: Данные для входа
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.DoctorLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешное создание
          schema:
            $ref: '#/definitions/models.DoctorAuthResponse'
        "400":
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/handlers.IncorrectFormatError'
        "401":
          description: Неверные учётные данные
          schema:
            $ref: '#/definitions/handlers.IncorrectDataError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/handlers.InternalServerError'
      summary: Вход в систему
      tags:
      - Auth
  /doctors/{doc_id}:
    get:
      consumes:
      - application/json
      description: Возвращает данные врача по ID
      parameters:
      - description: ID врача
        in: path
        name: doc_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Данные врача
          schema:
            $ref: '#/definitions/entities.Doctor'
        "400":
          description: Некорректный ID
          schema:
            $ref: '#/definitions/handlers.IncorrectDataError'
        "404":
          description: Врач не найден
          schema:
            $ref: '#/definitions/handlers.NotFoundError'
        "500":
          description: Внутренняя ошибка
          schema:
            $ref: '#/definitions/handlers.InternalServerError'
      summary: Получить врача по ID
      tags:
      - Doctor
    put:
      consumes:
      - application/json
      description: Обновляет информацию о враче
      parameters:
      - description: Данные для обновления
        in: body
        name: info
        required: true
        schema:
          $ref: '#/definitions/models.UpdateDoctorRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Обновленный врач
          schema:
            $ref: '#/definitions/entities.Doctor'
        "400":
          description: Некорректный запрос
          schema:
            $ref: '#/definitions/handlers.IncorrectFormatError'
        "404":
          description: Врач не найден
          schema:
            $ref: '#/definitions/handlers.NotFoundError'
        "422":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/handlers.ValidationError'
        "500":
          description: Внутренняя ошибка
          schema:
            $ref: '#/definitions/handlers.InternalServerError'
      summary: Обновить данные врача
      tags:
      - Doctor
  /emergency/{doc_id}:
    get:
      consumes:
      - application/json
      description: Возвращает список экстренных приёмов, назначенных врачу на указанную
        дату, с пагинацией
      parameters:
      - description: ID врача
        in: path
        name: doc_id
        required: true
        type: integer
      - description: Дата в формате YYYY-MM-DD
        in: query
        name: date
        type: string
      - default: 1
        description: Номер страницы
        in: query
        name: page
        type: integer
      - default: 5
        description: Количество записей на страницу
        in: query
        name: perPage
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Список приёмов
          schema:
            items:
              $ref: '#/definitions/models.PatientGroupShortResponse'
            type: array
        "400":
          description: Некорректный запрос
          schema:
            $ref: '#/definitions/handlers.IncorrectFormatError'
        "500":
          description: Внутренняя ошибка
          schema:
            $ref: '#/definitions/handlers.InternalServerError'
      summary: Получить группы пациентов по их коду или названию их организаций
      tags:
      - SMP
  /organizations:
    get:
      consumes:
      - application/json
      description: Возвращает список организаций с пагинацией
      parameters:
      - default: 1
        description: Номер страницы
        in: query
        name: page
        type: integer
      - default: 5
        description: Количество записей на страницу
        in: query
        name: perPage
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Список организаций
          schema:
            $ref: '#/definitions/models.OrganizationShortResponse'
        "400":
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/handlers.IncorrectFormatError'
        "401":
          description: Некорректный ID пользователя
          schema:
            $ref: '#/definitions/handlers.IncorrectDataError'
        "422":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/handlers.ValidationError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/handlers.InternalServerError'
      summary: Получить все организации
      tags:
      - Organizations
  /organizations/{org_id}/groups:
    get:
      consumes:
      - application/json
      description: Возвращает список групп пациентов конкретной организации с пагинацией
      parameters:
      - description: ID организации
        in: path
        name: org_id
        required: true
        type: integer
      - default: 1
        description: Номер страницы
        in: query
        name: page
        type: integer
      - default: 10
        description: Количество записей на страницу
        in: query
        name: perPage
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PatientGroupShortResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Получить группы пациентов организации
      tags:
      - PatientGroups
  /patients:
    get:
      consumes:
      - application/json
      description: |-
        Возвращает список всех существующих пациентов

        Работает фильтрация, сортировка и пагинация
      parameters:
      - description: |-
          Номер страницы
          (по умолчанию 1)
        in: query
        name: page
        type: integer
      - description: |-
          Количество записей на странице
          (по умолчанию 0 — без ограничения)
        in: query
        name: count
        type: integer
      - description: |-
          Фильтр в формате field.operation.value.
          Примеры:
          full_name.like.Иван - имя содержит 'Иван',
          birth_date.eq.1988-07-14 - точная дата рождения
        in: query
        name: filter
        type: string
      - description: |-
          Сортировка в формате field.direction.
          Примеры:
          full_name.asc - по алфавиту,
          id.desc - по убыванию ID пациента
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список пациентов
          schema:
            $ref: '#/definitions/models.PatientsListResponse'
        "400":
          description: Некорректные данные
          schema:
            $ref: '#/definitions/handlers.ResultError'
        "500":
          description: Внутренняя ошибка
          schema:
            $ref: '#/definitions/handlers.ResultError'
      summary: Получить список всех пациентов
      tags:
      - Patient
    post:
      consumes:
      - application/json
      description: Создает нового пациента с персональными и контактными данными
      parameters:
      - description: Данные пациента
        in: body
        name: info
        required: true
        schema:
          $ref: '#/definitions/models.CreatePatientRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Созданный пациент
          schema:
            $ref: '#/definitions/entities.Patient'
        "400":
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/handlers.IncorrectFormatError'
        "422":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/handlers.ValidationError'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/handlers.InternalServerError'
      summary: Создать нового пациента
      tags:
      - Patient
swagger: "2.0"
